services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - todo-network

  java-app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: todo-java-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todoapp
      SPRING_DATASOURCE_USERNAME: todouser
      SPRING_DATASOURCE_PASSWORD: todopassword
    depends_on:
      - mysql
    volumes:
      - ./java/src:/app/src
      - ./java/target:/app/target
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge
